FeriaVirtual-Web/FeriaVirtualWeb/Models/DataContext/TRANSPORTISTA.cs
//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FeriaVirtualWeb.Models.DataContext
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class TRANSPORTISTA
    {
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0}")]
        public decimal IDTRANSPORTISTA { get; set; }
        public string RUTTRANSPORTISTA { get; set; }
        public string NOMBRE { get; set; }
        public string TELEFONO { get; set; }
        [Display(Name = "TIPO TRANSPORTE")]
        public string TIPOTRANSPORTE { get; set; }
        public decimal ANCHO { get; set; }
        public decimal ALTO { get; set; }
        public decimal LARGO { get; set; }
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0}")]
        [Display(Name ="CAPACIDAD")]
        public decimal CAPACIDADCARGA { get; set; }
        public string REFRIGERACION { get; set; }
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0}")]
        [Display(Name = "N° SUBASTA")]
        public Nullable<decimal> SUBASTAID { get; set; }
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:C0}")]
        public Nullable<decimal> PRECIO { get; set; }
        public string ESTADOSUBASTA { get; set; }
        [Display(Name = "TRANSPORTE")]
        public List<TRANSPORTISTA> TRANSPORTELISTA { get; set; }
        [Display(Name = "REFRIGERACION")]
        public List<string> BoolRefrigeracionList { get; set; }

        public virtual SUBASTA SUBASTA { get; set; }
    }
}

FeriaVirtual-Web/FeriaVirtualWeb/Controllers/AdministradorController.cs
using FeriaVirtualWeb.Filter;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Net.Mail;
using System.Web.Mvc;
using FeriaVirtualWeb.Models.DataContext;
using FeriaVirtualWeb.Models.DataManager;
using FeriaVirtualWeb.Models.ViewModels;
using FeriaVirtualWeb.Reports;

namespace FeriaVirtualWeb.Controllers
{
    [UserAuthorization(Rol = 1)]
    public class AdministradorController : Controller
    {
        CollectionManager collection = new CollectionManager();
        public ActionResult OfertasTranportistas()
        {
            var usuario = (USUARIO)Session["usuario"];
            ViewBag.session = usuario.NOMBREUSUARIO;
            return View();
        }

        public ActionResult SubastasExternaList()
        {
            var subasta = collection.GetSubastaExternaToAdministrador();
            return View(subasta);
        }

        public ActionResult SubastasLocalList()
        {
            var subasta = collection.GetSubastaLocalToAdministrador();
            return View(subasta);
        }

        public ActionResult Transportistas(decimal id)
        {
            var oferta = collection.GetTransportistasOfertas(id);
            return View(oferta);
        }

        public ActionResult AceptarTransporte(decimal id)
        {
            var lowprice = collection.GetTransportistaLowPrice(id);
            var accept = collection.GetTransportistaByLowPrice(lowprice, id);
            return View(accept);
        }

        public JsonResult AceptarTransportePost(decimal transportista)
        {
            var adminM = new AdministradorManager();
            var accept = adminM.UpdateEstadoTransporteToAccept(transportista);
            return Json(accept);
        }

        public ActionResult ProcesosVentaExterna()
        {
            var usuario = (USUARIO)Session["usuario"];
            ViewBag.session = usuario.NOMBREUSUARIO;
            var listaP = collection.GetProcesoVentaExternaList();
            return View(listaP);
        }

        public ActionResult CotizacionDetalleProcesoVenta(decimal id)
        {
            var detalle = new ProcesoVentaViewModel();
            var listaProductores = new List<ProcesoVentaViewModel>();
            var listaPordenes = new List<PRODUCTO>();
            if (id != 0)
            {
                detalle = collection.GetMyPostulacionDetails(id);
                listaProductores = collection.GetProductorDatosbyOrdenId(id);
                listaPordenes = collection.GetMyProductsByOrders(id);
            }
            ViewBag.productores = listaProductores;
            ViewBag.productosOr = listaPordenes;
            return View(detalle);
        }

        public ActionResult DetalleProcesoVenta(decimal id)
        {
            var detalle = new ProcesoVentaViewModel();
            var listaProductores = new List<ProcesoVentaViewModel>();
            var listaPordenes = new List<PRODUCTO>();
            if (id != 0)
            {
                detalle = collection.GetMyPostulacionDetails(id);
                listaProductores = collection.GetProductorDatosbyOrdenId(id);
                listaPordenes = collection.GetMyProductsByOrders(id);
            }
            ViewBag.productores = listaProductores;
            ViewBag.productosOr = listaPordenes;
            return View(detalle);
        }

        public ActionResult DetalleProcesoVentaToDetalleAfterVenta(decimal id)
        {
            var detalle = new ProcesoVentaViewModel();
            var listaProductores = new List<ProcesoVentaViewModel>();
            var listaPordenes = new List<PRODUCTO>();
            if (id != 0)
            {
                detalle = collection.GetMyPostulacionDetails(id);
                listaProductores = collection.GetProductorDatosbyOrdenId(id);
                listaPordenes = collection.GetMyProductsByOrders(id);
            }
            ViewBag.productores = listaProductores;
            ViewBag.productosOr = listaPordenes;
            return View(detalle);
        }

        public JsonResult EnviarCotizacion(decimal id)
        {
            var ventaM = new VentaManager();
            var ordenM = new ClienteManager();
            var ordenid = collection.GetOrdenIdByProcedoId(id);
            var productosOr = ventaM.GetProductByOrden(ordenid);
            var listaProducto = ventaM.GetProductsWithCantidadAndPrecioToResumenVenta(productosOr);
            var cliente = collection.GetclienteByOrdenId(ordenid);
            var costoTotal = ventaM.GetCostoTotalProductsOrdesToCotizacion(ordenid);
            var estado = ordenM.ChangeEstadoCotizacionSent(ordenid);

            string productos = string.Empty;
            string paraPortal = "Favor de ACEPTAR o RECHAZAR esta cotizacion por medio de su portal en nuestra pagina";

            foreach (var item in listaProducto)
            {
                productos = productos + "<br/><hr/>" + "<table><tr><td>Producto:</td><td>" + "&nbsp;" + item.DESCRIPCION + "</td></tr>" +
                    "<tr><td>Cantidad Solicitada:</td><td>" + "&nbsp;" + item.CANTIDAD.ToString() + "</td></tr>" +
                    "<tr><td>Precio:</td><td>" + "&nbsp;" + "$" + item.PRECIO.ToString() + "</td></tr></table>";
            }

            string body = "<p>Estimado(a)" + " " + cliente.NOMBRE + " " + "hacemos envio de la cotizacion de su orden de compra numero" + " " + ordenid.ToString() + ":" +" </p>"
                    + productos + " " + "<br/>" + "<table><tr><td><strong>Costo Total:</strong></td><td>" + "&nbsp;" + "<strong>$</strong>" + "<strong>" + costoTotal.ToString() + "</strong>" + "</td></tr></table>" +
                    "<br/><p><strong>"+ paraPortal +"</strong></p>";

            MailMessage correo = new MailMessage();
            correo.From = new MailAddress("maipogrande77@gmail.com");
            correo.To.Add(cliente.CORREO);
            correo.Subject = "Cotizacion de Orden de Compra";
            correo.Body = body;
            correo.IsBodyHtml = true;
            correo.Priority = MailPriority.Normal;

            SmtpClient smtp = new SmtpClient();
            smtp.Host = "smtp.gmail.com";
            smtp.Port = 25;
            smtp.EnableSsl = true;
            smtp.UseDefaultCredentials = true;
            string mycorreo = "maipogrande77@gmail.com";
            string password = "maipo123";
            smtp.Credentials = new System.Net.NetworkCredential(mycorreo, password);

            smtp.Send(correo);

            return Json(id);
        }

        public ActionResult IngresarValoresDeVenta(decimal id)
        {
            var venta = new VentaViewModel();
            venta.PROCESOVENTA_IDPROCESOVENTA = id;
            venta.FECHA = DateTime.Now;
            var subastaid = collection.GetSubastaByProcesoVenta(id);
            var costoT = collection.GetCostoTranporteToVenta(subastaid);
            venta.COSTOTRANSPORTE = costoT;
            return View(venta);
        }

        [HttpPost]
        public ActionResult ResumenVenta(VentaViewModel venta)
        {
            var usuario = (USUARIO)Session["usuario"];
            ViewBag.session = usuario.NOMBREUSUARIO;
            var ventaM = new VentaManager();
            var insertVenta = new VENTA();
            if (venta != null)
            {
                insertVenta = ventaM.InsertNewVenta(venta);
            }
            var ventaDetalle = ventaM.GetAndInsertDetalisVenta(insertVenta);
            var ordenid = ventaM.GetOrdenIdByProcesoID(venta.PROCESOVENTA_IDPROCESOVENTA);
            var productosOr = ventaM.GetProductByOrden(ordenid);
            ViewBag.productos = ventaM.GetProductsWithCantidadAndPrecioToResumenVenta(productosOr);
            return View(ventaDetalle);
        }

        public JsonResult EnviarResumen(decimal id)
        {
            var ventaM = new VentaManager();
            var venta = collection.GetVentaByProcesoVenta(id);
            var ordenid = collection.GetOrdenIdByProcedoId(id);
            var productosOr = ventaM.GetProductByOrden(ordenid);
            var listaProducto = ventaM.GetProductsWithCantidadAndPrecioToResumenVenta(productosOr);
            var cliente = collection.GetclienteByOrdenId(ordenid);

            string productos = string.Empty;

            foreach (var item in listaProducto)
            {
                productos = productos + "<br/><hr/>" + "<table><tr><td>Producto:</td><td>" + "&nbsp;" + item.DESCRIPCION + "</td></tr>" +
                    "<tr><td>Cantidad Solicitada:</td><td>" + "&nbsp;" + item.CANTIDAD.ToString() + "</td></tr>" +
                    "<tr><td>Precio:</td><td>" + "&nbsp;" + "$" + item.PRECIO.ToString() + "</td></tr></table>";
            }

            string body = "<p>Estimado(a)" + " " + cliente.NOMBRE + " " + "los costos correspondientes a su orden numero" + " " + ordenid.ToString() + " " + "son: </p>"
                    + productos +" "+"<br/>"+ "<table><tr><td><strong>Costo Total:</strong></td><td>" + "&nbsp;" + "<strong>$</strong>" + "<strong>"+ venta.COSTOTOTAL.ToString() +"</strong>"+ "</td></tr></table>";

            MailMessage correo = new MailMessage();
            correo.From = new MailAddress("maipogrande77@gmail.com");
            correo.To.Add(cliente.CORREO);
            correo.Subject = "Resumen de venta de Orden de Compra";
            correo.Body = body;
            correo.IsBodyHtml = true;
            correo.Priority = MailPriority.Normal;

            SmtpClient smtp = new SmtpClient();
            smtp.Host = "smtp.gmail.com";
            smtp.Port = 25;
            smtp.EnableSsl = true;
            smtp.UseDefaultCredentials = true;
            string mycorreo = "maipogrande77@gmail.com";
            string password = "maipo123";
            smtp.Credentials = new System.Net.NetworkCredential(mycorreo, password);

            smtp.Send(correo);

            return Json(id);
        }

        public ActionResult HistorialVentas()
        {

FeriaVirtual-Web/FeriaVirtualWeb/Controllers/TransportistaController.cs
using System.Collections.Generic;
using System.Web.Mvc;
using FeriaVirtualWeb.Filter;
using FeriaVirtualWeb.Models.DataContext;
using FeriaVirtualWeb.Models.DataManager;

namespace FeriaVirtualWeb.Controllers
{
    [UserAuthorization(Rol = 4)]
    public class TransportistaController : Controller
    {
        CollectionManager collection = new CollectionManager();
        // GET: Transportista
        public ActionResult Transporte()
        {
            var usuario = (USUARIO)Session["usuario"];
            ViewBag.session = usuario.NOMBREUSUARIO;
            return View();
        }

        public ActionResult MyTransportes()
        {
            var newLista = new List<TRANSPORTISTA>();
            var usuario = (USUARIO)Session["usuario"];
            var transporte = collection.GetTransporte(usuario);
            foreach (var item in transporte)
            {
                newLista.Add(new TRANSPORTISTA()
                {
                    IDTRANSPORTISTA = item.IDTRANSPORTISTA,
                    TIPOTRANSPORTE = item.TIPOTRANSPORTE,
                    ANCHO = item.ANCHO,
                    ALTO = item.ALTO,
                    LARGO = item.LARGO,
                    CAPACIDADCARGA = item.CAPACIDADCARGA,
                    REFRIGERACION = item.REFRIGERACION == "1" ? "Si" : "No",
                });
            }
            return View(newLista);
        }

        public ActionResult AddNewTransporte()
        {
            var usuario = (USUARIO)Session["usuario"];
            var transporte = collection.GetMyTransporteByToNew(usuario);
            var newtransporte = new TRANSPORTISTA
            {
                IDTRANSPORTISTA = transporte.IDTRANSPORTISTA,
                RUTTRANSPORTISTA = transporte.RUTTRANSPORTISTA,
                NOMBRE = transporte.NOMBRE,
                TELEFONO = transporte.TELEFONO
            };

            return View(newtransporte);
        }

        public JsonResult AddNewTransportes(TRANSPORTISTA transportista)
        {
            var newtransporte = new TransportistaManager();
            return Json(newtransporte.InsertNewTransporte(transportista));
        }

        public ActionResult EditMyTransportes(decimal id)
        {
            var updateTrans = collection.GetMyTransporteById(id);
            return View(updateTrans);
        }

        public JsonResult EditMyTransporte(TRANSPORTISTA transp)
        {
            var updateTrans = new TRANSPORTISTA();
            var transM = new TransportistaManager();
            if(transp != null)
            {
                updateTrans = transM.UpdateTransporte(transp);
            }
            return Json(updateTrans);
        }

    }
}

FeriaVirtual-Web/FeriaVirtualWeb/Views/Administrador/AceptarTransporte.cshtml
@model FeriaVirtualWeb.Models.DataContext.TRANSPORTISTA

@{ 
    Layout = null;
}

<div>
    <h4>TRANSPORTISTA</h4>
    <hr />
    <table class="table table-condensed table-sm">
        <tr>
            <td>
                @Html.DisplayNameFor(model => model.IDTRANSPORTISTA)
            </td>

            <td>
                @Html.DisplayFor(model => model.IDTRANSPORTISTA)
            </td>
        </tr>
        <tr>
            <td>
                @Html.DisplayNameFor(model => model.NOMBRE)
            </td>

            <td>
                @Html.DisplayFor(model => model.NOMBRE)
            </td>
        </tr>
        <tr>
            <td>
                @Html.DisplayNameFor(model => model.TIPOTRANSPORTE)
            </td>

            <td>
                @Html.DisplayFor(model => model.TIPOTRANSPORTE)
            </td>
        </tr>
        <tr>
            <td>
                @Html.DisplayNameFor(model => model.ANCHO)
            </td>

            <td>
                @Html.DisplayFor(model => model.ANCHO)
            </td>
        </tr>
        <tr>
            <td>
                @Html.DisplayNameFor(model => model.ALTO)
            </td>

            <td>
                @Html.DisplayFor(model => model.ALTO)
            </td>
        </tr>
        <tr>
            <td>
                @Html.DisplayNameFor(model => model.LARGO)
            </td>

            <td>
                @Html.DisplayFor(model => model.LARGO)
            </td>
        </tr>
        <tr>
            <td>
                @Html.DisplayNameFor(model => model.CAPACIDADCARGA)
            </td>

            <td>
                @Html.DisplayFor(model => model.CAPACIDADCARGA)
            </td>
        </tr>
        <tr>
            <td>
                @Html.DisplayNameFor(model => model.REFRIGERACION)
            </td>

            <td>
                @Html.DisplayFor(model => model.REFRIGERACION)
            </td>
        </tr>
        <tr>
            <td>
                @Html.DisplayNameFor(model => model.PRECIO)
            </td>

            <td>
                @Html.DisplayFor(model => model.PRECIO)
            </td>
        </tr>  
    </table>
</div>
<p>
    <a href="#" class="btnAceptar btn btn-success notika-btn-success" data-id="@Model.IDTRANSPORTISTA">
        Aceptar
    </a>
</p>

<script>
    $(document).ready(function () {

        var btnAceptar = $(".btnAceptar");

        btnAceptar.click(function () {
            $.ajax({
                url: '@Url.Action("AceptarTransportePost", "Administrador")',
                type: "POST",
                dataType: 'html',
                data: { transportista: $(this).data("id") },
                beforeSend: function () {
                    btnAceptar.replaceWith("<img src='@Url.Content("~/assest/img/loading.gif")'>");
                },
                success: function (response) {
                    if (response) {
                        $("#exampleModalCenter").modal("hide");
                        toastr.options = {
                            "positionClass": "toast-top-right",
                            "timeOut": "4000",
                        }
                        toastr["success"]("El Tranporte ha sido Aceptado")
                    }
                }
            });
            return false;
        });
    });
</script>

FeriaVirtual-Web/FeriaVirtualWeb/Views/Administrador/DetalleProcesoVentaLocal.cshtml
@model List<FeriaVirtualWeb.Models.ViewModels.ProcesoVentaViewModel>

@{
    /**/

    Layout = null;
}

@using (Html.BeginForm("GenerarVentaLocal", "Administrador", FormMethod.Post, new { id = "form-ventalocal" }))
{
    <table class="table">
        <tr>
            <th>
                @Html.DisplayName("PRODUCTOR")
            </th>
            <th>
                @Html.DisplayName("PRODUCTO")
            </th>
            <th>
                @Html.DisplayName("PRECIO")
            </th>
            <th>
                @Html.DisplayName("CANTIDAD COMPRADA")
            </th>
            <th>
                @Html.DisplayName("CLIENTE")
            </th>
        </tr>

        @for (var i = 0; i < Model.Count(); i++)
        {
            @Html.HiddenFor(model => Model[i].NOMBREPRODUCTOR)
            @Html.HiddenFor(model => Model[i].DESCRIPCIONP)
            @Html.HiddenFor(model => Model[i].PRECIOP)
            @Html.HiddenFor(model => Model[i].CANTIDAD)
            @Html.HiddenFor(model => Model[i].NOMBRECLIENTE)
            @Html.HiddenFor(model => Model[i].PROCESO)
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => Model[i].NOMBREPRODUCTOR)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => Model[i].DESCRIPCIONP)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => Model[i].PRECIOP)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => Model[i].CANTIDAD)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => Model[i].NOMBRECLIENTE)
                </td>
            </tr>
        }

    </table>
    <div class="boton">
        <input type="submit" class="btnVentaL btn btn-success notika-btn-success" value="Ingresar Venta" />
        <div class="loadbuttonVL d-flex justify-content-center"></div>
    </div>
    
}

<script src="~/assest/js/bootstrap-select.js"></script>
<script src="~/assest/js/wow.min.js"></script>
<script src="~/assest/js/jquery-price-slider.js"></script>
<script src="~/assest/js/owl.carousel.min.js"></script>
<script src="~/assest/js/jquery.scrollUp.min.js"></script>
<script src="~/assest/js/jquery.meanmenu.js"></script>
<script src="~/assest/js/jquery.mCustomScrollbar.concat.min.js"></script>
<script src="~/assest/js/jquery.sparkline.min.js"></script>
<script src="~/assest/js/sparkline-active.js"></script>
<script src="~/assest/js/jquery.flot.js"></script>
<script src="~/assest/js/jquery.flot.resize.js"></script>
<script src="~/assest/js/flot-active.js"></script>
<script src="~/assest/js/jquery.knob.js"></script>
<script src="~/assest/js/jquery.appear.js"></script>
<script src="~/assest/js/knob-active.js"></script>
<script src="~/assest/js/jquery.todo.js"></script>
@*<script src="~/assest/js/waves.min.js"></script>
    <script src="~/assest/js/wave-active.js"></script>*@
<script src="~/assest/js/plugins.js"></script>
<script src="~/assest/js/main.js"></script>

<script>
    $(document).ready(function () {

        var form = $("#form-ventalocal");
        var btnVentaL = $(".btnVentaL");

        btnVentaL.click(function () {
            $.ajax({
                url: form.attr('action'),
                type: "POST",
                dataType: 'html',
                data: form.serialize(),
                beforeSend: function () {
                    btnVentaL.replaceWith($(".loadbuttonVL"));
                    $(".loadbuttonVL").html("<img src='@Url.Content("~/assest/img/loading.gif")'>");
                },
                success: function (response) {
                    if (response) {
                        toastr.options = {
                            "positionClass": "toast-top-right",
                            "timeOut": "4000",
                        }
                        toastr["success"]("La Venta Ha sido Generada Exitosamente")
                        $(".loadbuttonVL").remove();
                        $(".boton").append("<input type='submit' class='btnVentaL btn btn-success notika-btn-success' value='Ingresar Venta' />");
                    }
                }
            });
            return false;
        });
    });
</script>

FeriaVirtual-Web/FeriaVirtualWeb/Views/Administrador/DetalleProcesoVentaLocalAfterToVenta.cshtml
@model List<FeriaVirtualWeb.Models.ViewModels.ProcesoVentaViewModel>

@{
    /**/

    Layout = null;
}

@using (Html.BeginForm("GenerarVentaLocal", "Administrador", FormMethod.Post, new { id = "form-ventalocal" }))
{
    <table class="table">
        <tr>
            <th>
                @Html.DisplayName("PRODUCTOR")
            </th>
            <th>
                @Html.DisplayName("PRODUCTO")
            </th>
            <th>
                @Html.DisplayName("PRECIO")
            </th>
            <th>
                @Html.DisplayName("CANTIDAD COMPRADA")
            </th>
            <th>
                @Html.DisplayName("CLIENTE")
            </th>
        </tr>

        @for (var i = 0; i < Model.Count(); i++)
        {
            @Html.HiddenFor(model => Model[i].NOMBREPRODUCTOR)
            @Html.HiddenFor(model => Model[i].DESCRIPCIONP)
            @Html.HiddenFor(model => Model[i].PRECIOP)
            @Html.HiddenFor(model => Model[i].CANTIDAD)
            @Html.HiddenFor(model => Model[i].NOMBRECLIENTE)
            @Html.HiddenFor(model => Model[i].PROCESO)
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => Model[i].NOMBREPRODUCTOR)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => Model[i].DESCRIPCIONP)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => Model[i].PRECIOP)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => Model[i].CANTIDAD)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => Model[i].NOMBRECLIENTE)
                </td>
            </tr>
        }

    </table>

}

<script src="~/assest/js/bootstrap-select.js"></script>
<script src="~/assest/js/wow.min.js"></script>
<script src="~/assest/js/jquery-price-slider.js"></script>
<script src="~/assest/js/owl.carousel.min.js"></script>
<script src="~/assest/js/jquery.scrollUp.min.js"></script>
<script src="~/assest/js/jquery.meanmenu.js"></script>
<script src="~/assest/js/jquery.mCustomScrollbar.concat.min.js"></script>
<script src="~/assest/js/jquery.sparkline.min.js"></script>
<script src="~/assest/js/sparkline-active.js"></script>
<script src="~/assest/js/jquery.flot.js"></script>
<script src="~/assest/js/jquery.flot.resize.js"></script>
<script src="~/assest/js/flot-active.js"></script>
<script src="~/assest/js/jquery.knob.js"></script>
<script src="~/assest/js/jquery.appear.js"></script>
<script src="~/assest/js/knob-active.js"></script>
<script src="~/assest/js/jquery.todo.js"></script>
@*<script src="~/assest/js/waves.min.js"></script>
    <script src="~/assest/js/wave-active.js"></script>*@
<script src="~/assest/js/plugins.js"></script>
<script src="~/assest/js/main.js"></script>

FeriaVirtual-Web/FeriaVirtualWeb/Views/Administrador/Estadistics.cshtml
@{
    Layout = "~/Views/Shared/_LayoutAdministrador.cshtml";
    FeriaVirtualWeb.Models.DataContext.VENTA gananciaM = ViewBag.gananciaM;
}

<div class="breadcomb-area">
    <div class="row">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <div class="breadcomb-list">
                <div class="row">
                    <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                        <div class="breadcomb-wp">
                            <div class="breadcomb-icon">
                                <i class="notika-icon notika-bar-chart"></i>
                            </div>
                            <div class="breadcomb-ctn">
                                <h2>Estadisticas</h2>
                                <p>Revise las estadisticas de la empresa</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div id="piechart" style="width: 900px; height: 500px;"></div>
<br />
<div class="col-4 pb-3 pt-2" style="background-color:white;">
    <div class="wb-traffic-inner notika-shadow sm-res-mg-t-30 tb-res-mg-t-30 dk-res-mg-t-30">
        <div class="website-traffic-ctn">
            <h2>$<span class="counter">@gananciaM.GANANCIA</span></h2>
            <p>Venta N° @gananciaM.IDVENTA Tiene la Mayor Ganancia para la Empresa</p>
        </div>
        <div class="sparkline-bar-stats3">4,2,8,2,5,6,3,8,3,5,9,5</div>
    </div>
</div>
<script>
    $(document).ready(function () {
        $.ajax({
            type: 'POST',
            dataType: 'json',
            contentType: 'application/json',
            url: '@Url.Action("GetProcesosVentaCount","Administrador")',
            success: function (response) {
                google.charts.load('current', { 'packages': ['corechart'] });
                google.charts.setOnLoadCallback(function () {
                    drawChart(response);
                });
            }
        });
    });
    function drawChart(response) {
        var data = new google.visualization.DataTable();
        data.addColumn('string', 'TIPOPROCESO');
        data.addColumn('number', 'COUNT');
        var dataArray = [];
        $.each(response, function (i, obj) {
            dataArray.push([obj.TIPOPROCESO, obj.COUNT]);
        });
        data.addRows(dataArray);

        var options = {
            title: 'Cantidad de Procesos de Venta'
        };

        var chart = new google.visualization.PieChart(document.getElementById('piechart'));

        chart.draw(data, options);
    }
</script>