FeriaVirtual-Web/FeriaVirtualWeb/Controllers/ClienteController.cs
using System.Collections.Generic;
using System.Web.Mvc;
using FeriaVirtualWeb.Filter;
using FeriaVirtualWeb.Models.DataContext;
using FeriaVirtualWeb.Models.DataManager;

namespace FeriaVirtualWeb.Controllers
{
    [UserAuthorization(Rol = 3)]
    public class ClienteController : Controller
    {
        CollectionManager collection = new CollectionManager();
        public ActionResult ChooseProducts()
        {
            var usuario = (USUARIO)Session["usuario"];
            ViewBag.session = usuario.NOMBREUSUARIO;
            return View();
        }

        public ActionResult MyOrdersList()
        {
            var lista = new List<PRODUCTO>();
            var listaOrdenes = new List<ORDEN>();
            var usuario = (USUARIO)Session["usuario"];
            listaOrdenes = collection.GetMyOrderList(usuario);
            ViewBag.ordenList = listaOrdenes;
            lista = (List<PRODUCTO>)collection.GetProductosList();
            return View(listaOrdenes);
        }

        public ActionResult GetProductOfMyOrders(decimal id)
        {
            var detalles = collection.GetMyProductsByOrders(id); 
            return View(detalles);
        }

        public ActionResult ShowCotizacion(decimal id)
        {
            var ventaM = new VentaManager();
            var productosOr = ventaM.GetProductByOrden(id);
            var listaProducto = ventaM.GetProductsWithCantidadAndPrecioToResumenVenta(productosOr);
            var costoTotal = ventaM.GetCostoTotalProductsOrdesToCotizacion(id);
            var Orden = collection.GetOrdenByOrdenId(id);
            ViewBag.costoTotal = costoTotal;
            ViewBag.orden = Orden;
            return View(listaProducto);
        }

        public JsonResult ChangeEstadoCotizacion(ORDEN orden)
        {
            var clientM = new ClienteManager();
            var cambiaEstadoC = clientM.ChangeEstadoCotizacionAceptarORechazar(orden);
            var Neworden = new ORDEN
            {
                IDORDEN = cambiaEstadoC.IDORDEN,
                FECHA = cambiaEstadoC.FECHA,
                CLIENTE_RUTCLIENTE = cambiaEstadoC.CLIENTE_RUTCLIENTE,
                ESTADO = cambiaEstadoC.ESTADO
            };
            return Json(Neworden);
        }

        public ActionResult RecepcionDetails(decimal id)
        {
            var usuario = (USUARIO)Session["usuario"];
            ViewBag.session = usuario.NOMBREUSUARIO;
            var ventaM = new VentaManager();
            var productosOr = ventaM.GetProductByOrden(id);
            var pago = collection.GetPago(id);
            ViewBag.productos = ventaM.GetProductsWithCantidadAndPrecioToResumenVenta(productosOr);
            return View(pago);
        }

        public ActionResult Pagar(decimal id)
        {
            var usuario = (USUARIO)Session["usuario"];
            ViewBag.session = usuario.NOMBREUSUARIO;
            var ventaM = new VentaManager();
            var productosOr = ventaM.GetProductByOrden(id);
            var procesoByorden = collection.GetProcesoDecimalByOrden(id);
            var venta = collection.GetVentaByProcesoVenta(procesoByorden);
            ViewBag.productos = ventaM.GetProductsWithCantidadAndPrecioToResumenVenta(productosOr);
            return View(venta);
        }

        [HttpPost]
        public JsonResult FormalizarPago(VENTA venta)
        {
            var ordenid = collection.GetOrdenIdByProcedoId(venta.PROCESOVENTA_IDPROCESOVENTA);
            var pago = new PAGO
            {
                TOTAL = venta.COSTOTOTAL,
                ORDEN_IDORDEN = ordenid
            };
            var PagoM = new PagoManager();
            var insertPago = PagoM.InsertNewPago(pago);

            return Json(insertPago);
        }

        public ActionResult GetListToAddNewOrders()
        {
            var lista = (List<PRODUCTO>)collection.GetProductosList();
            return View(lista);
        }

        public JsonResult AddOrder(List<PRODUCTO> productos)
        {
            var productsSeleted = new List<PRODUCTO>();

            if (ModelState.IsValid)
            {
                productsSeleted = collection.GetProductsSelected(productos);
                var cliente = new ClienteManager();
                var usuario = (USUARIO)Session["usuario"];
                cliente.InsertNewProductoToOrder(productsSeleted, usuario);
            }
            else
            {
                return Json(null);
            }

            return Json(productsSeleted);
        }


        public ActionResult GetRecepcion(decimal id)
        {
            var ordenEstado = new ORDEN();
            if(id != 0)
            {
                ordenEstado = collection.GetEstadoOrden(id);
            }
            var ordenEnvio = new ORDEN
            {
                IDORDEN = ordenEstado.IDORDEN,
                ESTADO = "Recepcionado"
            };
            return View(ordenEnvio);
        }

        public JsonResult EditEstadoOrden(ORDEN orden)
        {
            var estado = new ClienteManager();
            var updateEstado = estado.UpdateEstadoOrden(orden);
            var updateNoDisposable = new ORDEN
            {
                IDORDEN = updateEstado.IDORDEN,
                CANTIDAD = updateEstado.CANTIDAD,
                FECHA = updateEstado.FECHA,
                CLIENTE_RUTCLIENTE = updateEstado.CLIENTE_RUTCLIENTE,
                ESTADO = updateEstado.ESTADO
            };
            return Json(updateNoDisposable);
        }
    }
}

FeriaVirtual-Web/FeriaVirtualWeb/Controllers/ConsultorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using FeriaVirtualWeb.Filter;
using FeriaVirtualWeb.Models.DataContext;
using FeriaVirtualWeb.Models.DataManager;
using FeriaVirtualWeb.Models.ViewModels;
using FeriaVirtualWeb.Reports;

namespace FeriaVirtualWeb.Controllers
{
    [UserAuthorization(Rol = 6)]
    public class ConsultorController : Controller
    {
        CollectionManager collection = new CollectionManager();
        public ActionResult GetReportes()
        {
            var usuario = (USUARIO)Session["usuario"];
            ViewBag.session = usuario.NOMBREUSUARIO;
            return View();
        }

        public ActionResult ExportPDFListaVentas()
        {
            var listadoVentas = collection.GetVentas();
            var listado = new ListadoVentas();
            byte[] bytesG = listado.PdfReport(listadoVentas);
            return File(bytesG, "application/pdf", "ListadoVentas.pdf");
        }

        public ActionResult ExportPDFListaOrdenes()
        {
            var listadoOrdenes = collection.GetOrdenesList();
            var listado = new ListadoOrdenes();
            byte[] bytesG = listado.PdfReport(listadoOrdenes);
            return File(bytesG, "application/pdf", "ListadoOrdenes.pdf");
        }

        public ActionResult ExportPDFSubastaExterna()
        {
            var listadoSubastaExterna = collection.GetSubastaExternaList();
            var listado = new ListadoSubastasPexterna();
            byte[] bytesG = listado.PdfReport(listadoSubastaExterna);
            return File(bytesG, "application/pdf", "ListadoSubastaExterna.pdf");
        }

        public ActionResult ExportPDFSubastaLocal()
        {
            var listadoSubastaLocal = collection.GetSubastaLocalList();
            var listado = new ListadoSubastasPLocal();
            byte[] bytesG = listado.PdfReport(listadoSubastaLocal);
            return File(bytesG, "application/pdf", "ListadoSubastaLocal.pdf");
        }

        // GET: Consultor/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Consultor/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Consultor/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Consultor/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Consultor/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Consultor/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

FeriaVirtual-Web/FeriaVirtualWeb/Controllers/ProcesoVentaController.cs
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using FeriaVirtualWeb.Filter;
using FeriaVirtualWeb.Models.DataContext;
using FeriaVirtualWeb.Models.DataManager;
using FeriaVirtualWeb.Models.ViewModels;

namespace FeriaVirtualWeb.Controllers
{
    [UserAuthorization(Rol = 5)]
    public class ProcesoVentaController : Controller
    {
        CollectionManager collection = new CollectionManager();
        public ActionResult ProcesoVentaList()
        {
            var usuario = (USUARIO)Session["usuario"];
            ViewBag.session = usuario.NOMBREUSUARIO;
            return View();
        }

        public ActionResult ProcesosVentaList()
        {
            var lista = collection.GetClientListProcesoVenta();
            return View(lista);
        }

        public ActionResult ProductosListAccordingProcesoVenta(decimal id)
        {
            var productos = new List<PRODUCTO>();
            productos = collection.GetProductClientByOrderAndProductorNull(id);
            return View(productos);
        }
   

        public JsonResult Postular(decimal orden)
        {
            var procesoManager = new ProcesoVentaManager();
            var productos = new List<PRODUCTO>();
            var pPostulacion = new List<PRODUCTO>();
            var newOrden = orden;
            var procesoOr = orden;
            var proceso = new PROCESOVENTA();
   
            productos = collection.GetProductClientByOrderAndProductorNull(newOrden);
            proceso = collection.GetProcesoByOrden(procesoOr);
            var usuario = (USUARIO)Session["usuario"];
            pPostulacion = collection.GetProductsProductorAccordingToProcesoVenta(productos, usuario);
            if (pPostulacion.Count() != 0)
            {
                var productsInserted = procesoManager.InsertProcesoVentaAccordingToUsuario(pPostulacion, proceso.IDPROCESOVENTA, newOrden);
                foreach (var item in productos)
                {
                    if (item.IDPROCESOVENTA == null)
                    {
                        procesoManager.InsertOrderToProceso(productos, proceso.IDPROCESOVENTA);
                    }
                }
                
                procesoManager.UpdateStockProductsAfterPostular(productos, usuario, proceso.IDPROCESOVENTA);
            }
          
            return Json(pPostulacion);
        }

        public ActionResult MyPostulaciones()
        {
            var usuario = (USUARIO)Session["usuario"];
            ViewBag.session = usuario.NOMBREUSUARIO;
            var listaP = collection.GetMyPostulaciones(usuario);
            return View(listaP);
        }

        public ActionResult MyPostulacionesDetails(decimal? id)
        {
            var idp = id;
            var detalle = new ProcesoVentaViewModel();
            var listaP = new List<PRODUCTO>();
            var usuario = (USUARIO)Session["usuario"];
            if (id != 0)
            {
                detalle = collection.GetMyPostulacionDetails(id);
            }

            listaP = collection.GetProductsListAccordingToPostulacion(idp, usuario);
            ViewBag.productos = listaP;
            return View(detalle);
        }
        
    }
}

FeriaVirtual-Web/FeriaVirtualWeb/Controllers/SubastaController.cs
using System.Linq;
using System.Web.Mvc;
using FeriaVirtualWeb.Filter;
using FeriaVirtualWeb.Models.DataContext;
using FeriaVirtualWeb.Models.DataManager;
using FeriaVirtualWeb.Models.ViewModels;

namespace FeriaVirtualWeb.Controllers
{
    [UserAuthorization(Rol = 4)]
    public class SubastaController : Controller
    {
        CollectionManager collection = new CollectionManager();
        // GET: Subasta
        public ActionResult SubastaList()
        {
            var usuario = (USUARIO)Session["usuario"];
            ViewBag.session = usuario.NOMBREUSUARIO;
            return View();
        }

        public ActionResult SubastasList()
        {
            var subasta = collection.GetSubastaExterna();
            return View(subasta);
        }

        public ActionResult SubastasListLocal()
        {
            var subasta = collection.GetSubastaLocal();
            return View(subasta);
        }

        public ActionResult MySubastas()
        {
            var usuario = (USUARIO)Session["usuario"];
            ViewBag.session = usuario.NOMBREUSUARIO;
            var listaSu = collection.GetMySubastasList(usuario);
            return View(listaSu);
        }

        public ActionResult GetDetailsMySubastas(decimal id)
        {
            var usuario = (USUARIO)Session["usuario"];
            var listaT = collection.GetTransportistaDetailsBySubasta(id, usuario);
            decimal? proceso = 0;
            var trans = new TRANSPORTISTA
            {
                TIPOTRANSPORTE = listaT.TIPOTRANSPORTE,
                ANCHO = listaT.ANCHO,
                ALTO = listaT.ALTO,
                LARGO = listaT.LARGO,
                CAPACIDADCARGA = listaT.CAPACIDADCARGA,
                REFRIGERACION = listaT.REFRIGERACION == "1" ? "Si" : "No",
                SUBASTAID = listaT.SUBASTAID,
                ESTADOSUBASTA = listaT.ESTADOSUBASTA,
                PRECIO = listaT.PRECIO
            };
            proceso = collection.GetProcesoIdBySubastaId(id);
            var detallesCli = collection.GetDatosClientByProcesoVenta(proceso);
            var detallesCliL = collection.GetDatosClientByProcesoVentaL(proceso);
            var clientedatos = new ProcesoVentaViewModel();

            if (detallesCli.Count() > 0)
            {
                ViewBag.datoscliente = detallesCli;
            }
            if(detallesCliL.Count() > 0)
            {
                ViewBag.datosclienteL = detallesCliL;
            }

            return View(trans);
        }

        public ActionResult ProductsAccordingToProcesoVenta(decimal id)
        {
            var subastaM = new SubastaManager();
            var datos = collection.GetDatosClientByProcesoVenta(id);
            var ordenid = subastaM.GetOrderIdByProcesoVentaId(id);
            var listaP = collection.GetProductClientByOrderAndProductorNull(ordenid);
            ViewBag.productos = listaP;
            return View(datos);
        }

        public ActionResult ProductsAccordingToProcesoVentaLocal(decimal id)
        {
            var subastaM = new SubastaManager();
            var idproceso = id;
            var datos = collection.GetDatosClientByProcesoVentaLocal(idproceso);
            var cliente = collection.GetDatosClienteByRutOfProducto(datos.RUTCLIENTELOCAL);
            var productor = collection.GetDatosClientByProcesoVentaL(datos.RUTCLIENTELOCAL, idproceso);
            var productosLocal = collection.GetProductosByRutClienteLocalAndProceso(cliente.RUTCLIENTE, idproceso);
            
            ViewBag.productos = productosLocal;
            return View(productor);
        }

        public ActionResult AddTransportAndPrecioToSubasta(decimal id)
        {
            var usuario = (USUARIO)Session["usuario"];
            var tipotransporte = collection.GetTransporte(usuario);
            var transportista = new TRANSPORTISTA();
            transportista = new TRANSPORTISTA
            {
                SUBASTAID = id,
                TRANSPORTELISTA = tipotransporte
            };
            return View(transportista);
        }

        public JsonResult Postular(TRANSPORTISTA trans)
        {
            var usuario = (USUARIO)Session["usuario"];
            var transIns = trans;
            var subastaIn = new SubastaManager();
            var transportista = new TRANSPORTISTA();
            var transExist = collection.GetSubastaTransporteIfExist(usuario, trans.SUBASTAID);
            if (trans != null && transExist == null)
            {
                transportista = subastaIn.InsertSubastaAccordingTransportista(usuario, transIns);
            }
            return Json(transportista);
        }

        public ActionResult GananciaProcesoExterno(decimal id)
        {
            var procesoid = collection.GetProcesoIdBySubastaId(id);
            var costoTransporte = collection.GetVentaByProcesoVenta(procesoid);
            return View(costoTransporte);
        }

    }
}

FeriaVirtual-Web/FeriaVirtualWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title  MAIPO GRANDE</title>
    <link rel="shortcut icon" type="image/x-icon" href="~/assest/img/favicon.ico">
    <link href="https://fonts.googleapis.com/css?family=Roboto:100,300,400,700,900" rel="stylesheet">
    <link href="~/assest/css/bootstrap.min.css" rel="stylesheet" />
    <link href="~/assest/css/all.min.css" rel="stylesheet" />
    <link href="~/assest/css/owl.carousel.css" rel="stylesheet" />
    <link href="~/assest/css/owl.theme.css" rel="stylesheet" />
    <link href="~/assest/css/owl.transitions.css" rel="stylesheet" />
    <link href="~/assest/css/meanmenu.min.css" rel="stylesheet" />
    <link href="~/assest/css/animate.css" rel="stylesheet" />
    <link href="~/assest/css/normalize.css" rel="stylesheet" />
    <link href="~/assest/css/waves.min.css" rel="stylesheet" />
    <link href="~/assest/css/button.css" rel="stylesheet" />
    <link href="~/assest/css/jquery.mCustomScrollbar.min.css" rel="stylesheet" />
    <link href="~/assest/css/notika-custom-icon.css" rel="stylesheet" />
    <link href="~/assest/css/chosen/chosen.css" rel="stylesheet" />
    <link href="~/assest/css/main.css" rel="stylesheet" />
    <link href="~/assest/css/style.css" rel="stylesheet" />
    <link href="~/assest/css/responsive.css" rel="stylesheet" />
    <link href="~/assest/css/mystiles.css" rel="stylesheet" />
    <script src="~/assest/js/jquery-3.3.1.min.js"></script>
    <link href="~/assest/css/toastr.min.css" rel="stylesheet" />
    <script src="~/assest/js/modernizr-2.8.3.js"></script>
</head>
<body>
    <div class="header-top-area">
        <div class="container">
            <div class="row">
                <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12">
                    <div class="logo-area">
                        <img src="~/assest/img/logomg.png" />
                    </div>
                </div>
                <div class="col-lg-8 col-md-8 col-sm-12 col-xs-12 d-flex align-items-center justify-content-end">
                    @{
                        var session = ViewBag.session;
                    }
                    <div class="d-flex justify-content-end m-3" style="color:#ffffff"><strong>Bienvenido(a)</strong>&nbsp;&nbsp;@session</div>
                    <img src="~/assest/img/user1.png" style="width:50px;height:50px" />
                    <div class="header-top-menu">
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- End Header Top Area -->
    <!-- Main Menu area start-->
    <div class="main-menu-area mg-tb-40">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <ul class="nav nav-tabs notika-menu-wrap menu-it-icon-pro">
                        <li>
                            <a href="@Url.Action("MyListProducts","Productor")" class="a-menu"><i class="notika-icon notika-house pr-1"></i>Inicio</a>
                        </li>
                        <li>
                            <a href="@Url.Action("ProcesoVentaList","ProcesoVenta")" class="a-menu"><i class="notika-icon notika-credit-card pr-1"></i>Proceso de Venta</a>
                        </li>
                        <li>
                            <a href="@Url.Action("GetMyVentasLocales","Productor")" class="a-menu"><i class="notika-icon notika-credit-card pr-1"></i>Procesos de Venta Local</a>
                        </li>
                        <li>
                            <a href="@Url.Action("MyPostulaciones","ProcesoVenta")" class="a-menu"><i class="notika-icon notika-form pr-1"></i>Historial de Postulaciones</a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <div class="container body-content" id="container" style="min-height:100vh">
        @RenderBody()
    </div>
    <div class="footer-copyright-area">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="footer-copy-right">
                        <p>
                            &copy; @DateTime.Now.Year - Mi aplicación Web ALTO MAIPO
                        </p>
                        <p class="pt-0">Correo de Contacto:&nbsp; maipogrande77@gmail.com</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script src="~/assest/js/jquery-3.3.1.min.js"></script>
    <script src="~/assest/js/modernizr-2.8.3.js"></script>
    <script src="~/assest/js/jquery.validate.min.js"></script>
    <script src="~/assest/js/jquery.validate.unobtrusive.min.js"></script>
    <script src="~/assest/js/bootstrap.min.js"></script>
    <script src="~/assest/js/popper.min.js"></script>
    <script src="~/assest/js/toastr.min.js"></script>
    <script src="~/assest/js/wow.min.js"></script>
    <script src="~/assest/js/jquery-price-slider.js"></script>
    <script src="~/assest/js/owl.carousel.min.js"></script>
    <script src="~/assest/js/jquery.scrollUp.min.js"></script>
    <script src="~/assest/js/jquery.meanmenu.js"></script>
    <script src="~/assest/js/jquery.mCustomScrollbar.concat.min.js"></script>
    <script src="~/assest/js/jquery.sparkline.min.js"></script>
    <script src="~/assest/js/sparkline-active.js"></script>
    <script src="~/assest/js/jquery.flot.js"></script>
    <script src="~/assest/js/jquery.flot.resize.js"></script>
    <script src="~/assest/js/flot-active.js"></script>
    <script src="~/assest/js/jquery.knob.js"></script>
    <script src="~/assest/js/jquery.appear.js"></script>
    <script src="~/assest/js/knob-active.js"></script>
    <script src="~/assest/js/jquery.todo.js"></script>
    <script src="~/assest/js/waves.min.js"></script>
    <script src="~/assest/js/wave-active.js"></script>
    <script src="~/assest/js/plugins.js"></script>
    <script src="~/assest/js/main.js"></script>
</body>
</html>

FeriaVirtual-Web/FeriaVirtualWeb/Views/Shared/_LayoutClienteExterno.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width">
    <title>@ViewBag.Title - Mi aplicación ASP.NET</title>
    <link rel="shortcut icon" type="image/x-icon" href="~/assest/img/favicon.ico">
    <link href="https://fonts.googleapis.com/css?family=Roboto:100,300,400,700,900" rel="stylesheet">
    <link href="~/assest/css/bootstrap.min.css" rel="stylesheet" />
    <link href="~/assest/css/all.min.css" rel="stylesheet" />
    <link href="~/assest/css/owl.carousel.css" rel="stylesheet" />
    <link href="~/assest/css/owl.theme.css" rel="stylesheet" />
    <link href="~/assest/css/owl.transitions.css" rel="stylesheet" />
    <link href="~/assest/css/meanmenu.min.css" rel="stylesheet" />
    <link href="~/assest/css/animate.css" rel="stylesheet" />
    <link href="~/assest/css/normalize.css" rel="stylesheet" />
    <link href="~/assest/css/waves.min.css" rel="stylesheet" />
    <link href="~/assest/css/button.css" rel="stylesheet" />
    <link href="~/assest/css/jquery.mCustomScrollbar.min.css" rel="stylesheet" />
    <link href="~/assest/css/notika-custom-icon.css" rel="stylesheet" />
    <link href="~/assest/css/chosen/chosen.css" rel="stylesheet" />
    <link href="~/assest/css/main.css" rel="stylesheet" />
    <link href="~/assest/css/style.css" rel="stylesheet" />
    <link href="~/assest/css/responsive.css" rel="stylesheet" />
    <link href="~/assest/css/mystiles.css" rel="stylesheet" />
    <script src="~/assest/js/jquery-3.3.1.min.js"></script>
    <link href="~/assest/css/toastr.min.css" rel="stylesheet" />
    <script src="~/assest/js/modernizr-2.8.3.js"></script>
</head>
<body>
    <div class="header-top-area">
        <div class="container">
            <div class="row">
                <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12">
                    <div class="logo-area">
                        <img src="~/assest/img/logomg.png" />
                    </div>
                </div>
                <div class="col-lg-8 col-md-8 col-sm-12 col-xs-12 d-flex align-items-center justify-content-end">
                    @{
                        var session = ViewBag.session;
                    }
                    <div class="d-flex justify-content-end m-3" style="color:#ffffff"><strong>Bienvenido(a)</strong>&nbsp;&nbsp;@session</div>&nbsp;&nbsp;
                    <img src="~/assest/img/user1.png" style="width:50px;height:50px" />
                    <div class="header-top-menu">

                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- End Header Top Area -->
    <!-- Main Menu area start-->
    <div class="main-menu-area mg-tb-40">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <ul class="nav nav-tabs notika-menu-wrap menu-it-icon-pro">
                        <li>
                            <a href="@Url.Action("ChooseProducts","Cliente")" class="a-menu"><i class="notika-icon notika-house"></i>Inicio</a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <div class="container body-content" id="container" style="min-height:100vh">
        @RenderBody()
    </div>
    <div class="footer-copyright-area">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="footer-copy-right">
                        <p>
                            &copy; @DateTime.Now.Year - Mi aplicación Web ALTO MAIPO
                        </p>
                        <p class="pt-0">Correo de Contacto:&nbsp; maipogrande77@gmail.com</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script src="~/assest/js/jquery-3.3.1.min.js"></script>
    <script src="~/assest/js/modernizr-2.8.3.js"></script>
    <script src="~/assest/js/jquery.validate.min.js"></script>
    <script src="~/assest/js/jquery.validate.unobtrusive.min.js"></script>
    <script src="~/assest/js/bootstrap.min.js"></script>
    <script src="~/assest/js/toastr.min.js"></script>
    <script src="~/assest/js/wow.min.js"></script>
    <script src="~/assest/js/jquery-price-slider.js"></script>
    <script src="~/assest/js/owl.carousel.min.js"></script>
    <script src="~/assest/js/jquery.scrollUp.min.js"></script>
    <script src="~/assest/js/jquery.meanmenu.js"></script>
    <script src="~/assest/js/jquery.mCustomScrollbar.concat.min.js"></script>
    <script src="~/assest/js/jquery.sparkline.min.js"></script>
    <script src="~/assest/js/sparkline-active.js"></script>
    <script src="~/assest/js/jquery.flot.js"></script>
    <script src="~/assest/js/jquery.flot.resize.js"></script>
    <script src="~/assest/js/flot-active.js"></script>
    <script src="~/assest/js/jquery.knob.js"></script>
    <script src="~/assest/js/jquery.appear.js"></script>
    <script src="~/assest/js/knob-active.js"></script>
    <script src="~/assest/js/jquery.todo.js"></script>
    @*<script src="~/assest/js/waves.min.js"></script>
    <script src="~/assest/js/wave-active.js"></script>*@
    <script src="~/assest/js/plugins.js"></script>
    <script src="~/assest/js/main.js"></script>
</body>
</html>