FeriaVirtual-Web/FeriaVirtualWeb/Models/DataContext/PRODUCTOR.cs
//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FeriaVirtualWeb.Models.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCTOR
    {
        public PRODUCTOR()
        {
            this.PRODUCTO = new HashSet<PRODUCTO>();
        }
    
        public string RUTPRODUCTOR { get; set; }
        public string NOMBRE { get; set; }
        public string TELEFONO { get; set; }
        public string CORREO { get; set; }
        public string DIRECCION { get; set; }
        public string CIUDAD { get; set; }
        public string CONTRATO { get; set; }
        public System.DateTime FECHAINICIOCONTRATO { get; set; }
        public System.DateTime FECHATERMINOCONTRATO { get; set; }
        public string ESTADOCONTRATO { get; set; }
        public Nullable<decimal> PROCESOID { get; set; }

        public virtual ICollection<PRODUCTO> PRODUCTO { get; set; }
    }
}

FeriaVirtual-Web/FeriaVirtualWeb/Controllers/ProductorController.cs
using System.Collections.Generic;
using System.Web.Mvc;
using FeriaVirtualWeb.Models.DataManager;
using FeriaVirtualWeb.Models.DataContext;
using FeriaVirtualWeb.Filter;
using FeriaVirtualWeb.Reports;


namespace FeriaVirtualWeb.Controllers
{
    [UserAuthorization(Rol = 5)]
    public class ProductorController : Controller
    {
        CollectionManager collection = new CollectionManager();
        
        public ActionResult MyListProducts()
        {
            var usuario = (USUARIO)Session["usuario"];
            ViewBag.session = usuario.NOMBREUSUARIO;
            return View();
        }

        public ActionResult MyProductsListProcesoExterno()
        {
            var usuario = (USUARIO)Session["usuario"];
            var lista = collection.GetMyProductosList(usuario);
            return View(lista);
        }

        public ActionResult MyProductsListProcesoLocal()
        {
            var usuario = (USUARIO)Session["usuario"];
            var listaPLocal = collection.GetMyProductListProcesoLocal(usuario);
            return View(listaPLocal);
        }

        public ActionResult GetListToAddNewProductos()
        {
            var listaVacia = collection.GetProductosList();
            return View(listaVacia);
        }

        public JsonResult AddNewProductos(List<PRODUCTO> productos)
        {
            var productsSeleted = new List<PRODUCTO>();
            var productosList = new List<PRODUCTO>();
            var productosListNoDiposable = new List<PRODUCTO>();
            var newProducto = new PRODUCTO();

            if (ModelState.IsValid)
            {
                productsSeleted = collection.GetProductosListSelected(productos);
                var productor = new ProductorManager();
                var usuario = (USUARIO)Session["usuario"];
                foreach (var item in productsSeleted)
                {
                    if (collection.GetProductosListIfExternoExist(item, usuario))
                    {
                        newProducto = productor.InsertNewProducto(item, usuario);
                        productosList.Add(newProducto);
                    }
                    else
                    {
                        newProducto = productor.UpdateProducto(item, usuario);
                        productosList.Add(newProducto);
                    }
                    
                }
            }
            else
            {
                return Json(null);
            }

            foreach (var item in productosList)
            {
                productosListNoDiposable.Add(new PRODUCTO()
                {
                    IDPRODUCTO = item.IDPRODUCTO,
                    DESCRIPCION = item.DESCRIPCION,
                    PRECIO = item.PRECIO,
                    STOCK = item.STOCK,
                    TIPOVENTA = item.TIPOVENTA
                });
            }
            
            return Json(productosListNoDiposable);
        }

        public ActionResult EditProductos(decimal id)
        {
            var idEdit = collection.GetProductToEdit(id);
            return View(idEdit);
        }

        public JsonResult AddProductoEditado(PRODUCTO producto)
        {
            var productoEdit = new ProductorManager();
            var productoR = productoEdit.UpdateProducto(producto);
            var productoActualizado = new PRODUCTO
            {
                IDPRODUCTO = productoR.IDPRODUCTO,
                DESCRIPCION = productoR.DESCRIPCION,
                PRECIO = productoR.PRECIO,
                STOCK = productoR.STOCK
            };

            return Json(productoActualizado);
        }

        public ActionResult DeleteProduct(decimal id)
        {
            var productoDel = new PRODUCTO();
            if (id != 0)
            {
                productoDel = collection.GetProductByIdProducto(id);
            }
            return View(productoDel);
        }

        public JsonResult DeleteMyProduct(PRODUCTO producto)
        {
            var productorM = new ProductorManager();
            var productoDelete = new PRODUCTO();
            if (producto != null)
            {
                productoDelete = productorM.DeleteProduct(producto);
            }

            return Json(productoDelete);
        }

        public ActionResult GetMyProductsSelledAndProfit(decimal id)
        {
            var idproceso = id;
            var usuario = (USUARIO)Session["usuario"];
            var listaPAceppted = collection.GetMyProductsAccepted(usuario, idproceso);
            var listaPAcceptedtotales = collection.GetProductsAccepted(idproceso);
            var sumaPrecios = collection.TotalSumOfPrecioOfProductorAccordingToOneSell(listaPAceppted);

            var ventaByProceso = collection.GetVentaByProcesoVenta(idproceso);
            var ganancia = collection.GetMyProfit(listaPAcceptedtotales, ventaByProceso, sumaPrecios, usuario);
            return View(ganancia);
        }

        public ActionResult ExportPDFGanancias(decimal id)
        {
            var gananciaR = new GananciasProductor();
            byte[] bytesG = gananciaR.PdfReport(Ganancia(id));
            return File(bytesG,"application/pdf", "ReporteGanancia.pdf");
        }

        private VENTA Ganancia(decimal id)
        {
            var idproceso = id;
            var usuario = (USUARIO)Session["usuario"];
            var listaPAceppted = collection.GetMyProductsAccepted(usuario, idproceso);
            var listaPAcceptedtotales = collection.GetProductsAccepted(idproceso);
            var sumaPrecios = collection.TotalSumOfPrecioOfProductorAccordingToOneSell(listaPAceppted);

            var ventaByProceso = collection.GetVentaByProcesoVenta(idproceso);
            var ganancia = collection.GetMyProfit(listaPAcceptedtotales, ventaByProceso, sumaPrecios, usuario);
            return ganancia;
        }

        public ActionResult GetMyVentasLocales()
        {
            var usuario = (USUARIO)Session["usuario"];
            ViewBag.session = usuario.NOMBREUSUARIO;
            var misPrLocales = collection.GetMyProcesoVentaLocal(usuario);
            
            return View(misPrLocales);
        }

        public ActionResult GetProductComprados(decimal id)
        {
            var usuario = (USUARIO)Session["usuario"];
            var misPlocales = collection.GetMyProductListProcesoLocalComprados(usuario, id);
            return View(misPlocales);
        }

        public ActionResult GetGananciaLocales(decimal id)
        {
            var usuario = (USUARIO)Session["usuario"];
            var misPlocales = (List<PRODUCTO>)collection.GetMyProductListProcesoLocalComprados(usuario, id);
            var pagoNeto = collection.GetPagoLocalNeto(misPlocales);
            var ventaByProceso = collection.GetVentaByProcesoVenta(id);
            var pagoTotal = collection.GetPagoLocalTotal(pagoNeto, ventaByProceso);

            ViewBag.venta = ventaByProceso;
            ViewBag.pago = pagoTotal;
            return View(misPlocales);
        }
    }
}

FeriaVirtual-Web/FeriaVirtualWeb/Views/Productor/DeleteProduct.cshtml
@model FeriaVirtualWeb.Models.DataContext.PRODUCTO

@{
    Layout = null;
}

@using (Html.BeginForm("DeleteMyProduct", "Productor", FormMethod.Post, new { id = "form-eliminar" }))
{
    <div>
        @Html.HiddenFor(model => model.IDPRODUCTO)
        <div>
            <p>
                ¿Esta Seguro de Eliminar el Producto?
            </p>
        </div>

        <div>
            <input type="submit" value="Eliminar" class="btn btn-success notika-btn-success" id="btnEliminar"/>
            <div class="loaddelete d-flex justify-content-center"></div>
        </div>
    </div>

}

<script>
    $(document).ready(function () {

        var form = $("#form-eliminar");
        var botonDelete = $("#btnEliminar");

        botonDelete.click(function () {
            $.ajax({
                url: form.attr('action'),
                type: "POST",
                dataType: 'html',
                data: form.serialize(),
                beforeSend: function () {
                    botonDelete.replaceWith($(".loaddelete"));
                    $(".loaddelete").html("<img src='@Url.Content("~/assest/img/loading.gif")'>");
                },
                success: function (response) {
                    if (response) {
                        $("#exampleModalCenter").modal("hide");
                        toastr.options = {
                            "positionClass": "toast-top-right",
                            "timeOut": "4000",
                        }
                        toastr["success"]("El Producto ha sido Eliminado Exitosamente")
                        if ($("#externoid").hasClass("active")) {
                            $("#externoid").trigger("click");
                        } else {
                            $("#localid").trigger("click");
                        }
                        
                    }
                }
            });
            return false;                 
        });
    });
</script>

FeriaVirtual-Web/FeriaVirtualWeb/Views/Productor/EditProductos.cshtml
@model FeriaVirtualWeb.Models.DataContext.PRODUCTO

@{
    Layout = null;
}

@using (Html.BeginForm("AddProductoEditado", "Productor", FormMethod.Post, new { id = "form-actualizar" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal col-md-7 m-auto">
        <h5 class="d-flex justify-content-center">Editar Producto</h5>
        <br />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        @Html.HiddenFor(model => model.IDPRODUCTO)

        <div class="form-group">
            @Html.LabelFor(model => model.DESCRIPCION, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="nk-int-st">
                <div class="col-md-12">
                    @Html.EditorFor(model => model.DESCRIPCION, new { htmlAttributes = new { @class = "form-control", disabled = "disabled" } })
                    @Html.ValidationMessageFor(model => model.DESCRIPCION, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PRECIO, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="nk-int-st">
                <div class="col-md-12">
                    @Html.EditorFor(model => model.PRECIO, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.PRECIO, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.STOCK, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="nk-int-st">
                <div class="col-md-12">
                    @Html.EditorFor(model => model.STOCK, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.STOCK, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>


        <div class="form-group">
            <div class="col-md-offset-2 col-md-12">
                <input type="submit" value="Actualizar" class="btn btn-success notika-btn-success col" id="btnActualizar" />
                <div class="loadbutton d-flex justify-content-center"></div>
            </div>
        </div>
    </div>
}


<script src="~/assest/js/bootstrap-select.js"></script>
<script src="~/assest/js/wow.min.js"></script>
<script src="~/assest/js/jquery-price-slider.js"></script>
<script src="~/assest/js/owl.carousel.min.js"></script>
<script src="~/assest/js/jquery.scrollUp.min.js"></script>
<script src="~/assest/js/jquery.meanmenu.js"></script>
<script src="~/assest/js/jquery.mCustomScrollbar.concat.min.js"></script>
<script src="~/assest/js/jquery.sparkline.min.js"></script>
<script src="~/assest/js/sparkline-active.js"></script>
<script src="~/assest/js/jquery.flot.js"></script>
<script src="~/assest/js/jquery.flot.resize.js"></script>
<script src="~/assest/js/flot-active.js"></script>
<script src="~/assest/js/jquery.knob.js"></script>
<script src="~/assest/js/jquery.appear.js"></script>
<script src="~/assest/js/knob-active.js"></script>
<script src="~/assest/js/jquery.todo.js"></script>
@*<script src="~/assest/js/waves.min.js"></script>
    <script src="~/assest/js/wave-active.js"></script>*@
<script src="~/assest/js/plugins.js"></script>
<script src="~/assest/js/main.js"></script>


<script>
    $(document).ready(function () {

        var form = $("#form-actualizar");
        var botonAgregar = $("#btnActualizar");

        botonAgregar.click(function () {
            $.ajax({
                url: form.attr('action'),
                type: "POST",
                dataType: 'html',
                data: form.serialize(),
                beforeSend: function () {
                    botonAgregar.replaceWith($(".loadbutton"));
                    $(".loadbutton").html("<img src='@Url.Content("~/assest/img/loading.gif")'>");
                },
                success: function (response) {
                    if (response) {
                        $("#exampleModalCenter").modal("hide");
                        toastr.options = {
                            "positionClass": "toast-top-right",
                            "timeOut": "4000",
                        }
                        toastr["success"]("Su Producto ha sido Actualizado Exitosamente")
                        if ($("#externoid").hasClass("active")) {
                            $("#externoid").trigger("click");
                        } else {
                            $("#localid").trigger("click");
                        }

                    }
                }
            });
            return false;
        });
    });
</script>

FeriaVirtual-Web/FeriaVirtualWeb/Views/Productor/GetGananciaLocales.cshtml
@model IEnumerable<FeriaVirtualWeb.Models.DataContext.PRODUCTO>

@{ 
    Layout = null;
    decimal? Pago = ViewBag.pago;
    FeriaVirtualWeb.Models.DataContext.VENTA venta = ViewBag.venta;
}

<div class="d-flex justify-content-center">@Html.DisplayName("Productos Comprados")</div>
<br />
<table class="table table-condensed">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.DESCRIPCION)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PRECIO)
        </th> 
        <th>
            @Html.DisplayNameFor(model => model.CANTIDAD)
        </th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.DESCRIPCION)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.PRECIO)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CANTIDAD)
        </td>
    </tr>
}

</table>
<hr />
<div class="d-flex justify-content-center">@Html.DisplayName("Descuento")</div>
<table class="table table-condensed">

    <tr>
        <td>
            @Html.DisplayName("COSTO TRANSPORTE")
        </td>
        <td>
            @Html.DisplayFor(model => venta.COSTOTRANSPORTE)
        </td>
    </tr>
    <tr>
        <td>
            @Html.DisplayName("COMISION EMPRESA")
        </td>
        <td>
            @Html.DisplayFor(model => venta.GANANCIA)
        </td>
    </tr>
</table>
<hr />
<table class="table table-condensed">
    <tr>
        <td>
            @Html.DisplayName("PAGO TOTAL") 
        </td>
        <td>
            @("$" + Pago)
        </td>
    </tr>
</table>
    

FeriaVirtual-Web/FeriaVirtualWeb/Views/Productor/GetListToAddNewProductos.cshtml
@model List<FeriaVirtualWeb.Models.DataContext.PRODUCTO>

@{
    Layout = null;
}


@using (Html.BeginForm("AddNewProductos", "Productor", FormMethod.Post, new { id = "form-productos" }))
{
    <div class="pb-4 pl-5 pr-5" >
        <table class="table table-condensed">
            <tr>
                <th>
                    @Html.DisplayName("DESCRIPCION")
                </th>
                <th>
                    @Html.DisplayName("PRECIO")
                </th>
                <th>
                    @Html.DisplayName("STOCK")
                </th>
                <th>
                    @Html.DisplayName("TIPO VENTA")
                </th>
            </tr>
            @for (var i = 0; i < Model.Count(); i++)
            {
                @Html.HiddenFor(modelItem => Model[i].IDPRODUCTO, new { id = "idprod" })
                @Html.HiddenFor(modelItem => Model[i].DESCRIPCION, new { id = "descrip" })
                <tr>
                    <td>
                        <div style="height:37px;" class="d-flex align-items-end">
                            @Html.DisplayFor(modelItem => Model[i].DESCRIPCION, new { id = "descripcion" })
                        </div>
                    </td>
                    <td>
                        <div class="nk-int-st">
                            @Html.EditorFor(modelItem => Model[i].PRECIO, new { htmlAttributes = new { @class = "form-control", autocomplete = "off" } })
                        </div>
                    </td>
                    <td>
                        <div class="nk-int-st">
                            @Html.EditorFor(modelItem => Model[i].STOCK, new { htmlAttributes = new { @class = "form-control", autocomplete = "off" } })
                        </div>
                    </td>
                    <td>
                        <div class="chosen-select-act fm-cmp-mg d-flex align-items-end" style="height:37px;">
                            @Html.DropDownListFor(modelItem => Model[i].TIPOVENTA, new List<SelectListItem> { new SelectListItem { Text = "Seleccione", Value = "Seleccione", Disabled = true, Selected = true }, new SelectListItem { Text = "Externo", Value = "Externo" }, new SelectListItem { Text = "Local", Value = "Local" } },
                            new { @class = "chosen form-control" })
                        </div>
                    </td>
                </tr>

            }
        </table>
        <button type="submit" class="btnIngresarP btn btn-success notika-btn-success col" id="btnIngresarP">Agregar</button>
        <div class="loadbutton d-flex justify-content-center"></div>
    </div>
    
}


<script src="~/assest/js/wow.min.js"></script>
<script src="~/assest/js/jquery-price-slider.js"></script>
<script src="~/assest/js/owl.carousel.min.js"></script>
<script src="~/assest/js/jquery.scrollUp.min.js"></script>
<script src="~/assest/js/chosen.jquery.js"></script>
<script src="~/assest/js/jquery.meanmenu.js"></script>
<script src="~/assest/js/jquery.mCustomScrollbar.concat.min.js"></script>
<script src="~/assest/js/jquery.sparkline.min.js"></script>
<script src="~/assest/js/sparkline-active.js"></script>
<script src="~/assest/js/jquery.flot.js"></script>
<script src="~/assest/js/jquery.flot.resize.js"></script>
<script src="~/assest/js/flot-active.js"></script>
<script src="~/assest/js/jquery.knob.js"></script>
<script src="~/assest/js/jquery.appear.js"></script>
<script src="~/assest/js/knob-active.js"></script>
<script src="~/assest/js/jquery.todo.js"></script>
@*<script src="~/assest/js/waves.min.js"></script>
    <script src="~/assest/js/wave-active.js"></script>*@
<script src="~/assest/js/plugins.js"></script>
<script src="~/assest/js/main.js"></script>

<script>
    $(document).ready(function () {

        var form = $("#form-productos");
        var botonAgregar = $(".btnIngresarP");

        $("#btnIngresarP").click(function () {
            $.ajax({
                url: form.attr('action'),
                type: "POST",
                dataType: 'html',
                data: form.serialize(),
                beforeSend: function () {
                    botonAgregar.replaceWith($(".loadbutton"));
                    $(".loadbutton").html("<img src='@Url.Content("~/assest/img/loading.gif")'>");
                },
                success: function (response) {
                    console.log(response);
                    if (response) {
                        $("#exampleModalCenter").modal("hide");
                        toastr.options = {
                            "positionClass": "toast-top-right",
                            "timeOut": "4000",
                        }
                        toastr["success"]("Sus Productos han sido Agregados Exitosamente")
                        if ($("#externoid").hasClass("active")) {
                            $("#externoid").trigger("click");
                        } else {
                            $("#localid").trigger("click");
                        }
                    }
                }
            });
            return false;
        });
    });
</script>

FeriaVirtual-Web/FeriaVirtualWeb/Views/Productor/GetMyProductsSelledAndProfit.cshtml
@model FeriaVirtualWeb.Models.DataContext.VENTA

@{ 
    Layout = null;
}

<div>
    <h5 class="d-flex justify-content-center">Ganancias</h5>
    <hr />
    <table class="table table-condensed">
        <tr>
            <td>
                @Html.DisplayNameFor(model => model.PROCESOVENTA_IDPROCESOVENTA)
            </td>

            <td>
                @Html.DisplayFor(model => model.PROCESOVENTA_IDPROCESOVENTA)
            </td>
        </tr>
        <tr>
            <td>
                @Html.DisplayNameFor(model => model.IMPUESTOADUANA)
            </td>

            <td>
                @Html.DisplayFor(model => model.IMPUESTOADUANA)
            </td>
        </tr>
        <tr>
            <td>
                @Html.DisplayNameFor(model => model.COSTOTRANSPORTE)
            </td>

            <td>
                @Html.DisplayFor(model => model.COSTOTRANSPORTE)
            </td>
        </tr>
        <tr>
            <td>
                @Html.DisplayNameFor(model => model.COMISIONEMPRESA)
            </td>

            <td>
                @Html.DisplayFor(model => model.COMISIONEMPRESA)
            </td>
        </tr>
        <tr>
            <td>
                @Html.DisplayNameFor(model => model.GANANCIAPRODUCTORNETA)
            </td>

            <td>
                @Html.DisplayFor(model => model.GANANCIAPRODUCTORNETA)
            </td>
        </tr>
        <tr>
            <td>
                @Html.DisplayNameFor(model => model.GANANCIATOTAL)
            </td>

            <td>
                @Html.DisplayFor(model => model.GANANCIATOTAL)
            </td>
        </tr>
    </table>
</div>

<div>
    @Html.ActionLink("Exportar PDF", "ExportPDFGanancias", new { id = Model.PROCESOVENTA_IDPROCESOVENTA }, new { @class = "btn btn-success notika-btn-success" })
</div>

FeriaVirtual-Web/FeriaVirtualWeb/Views/Productor/GetMyVentasLocales.cshtml
@model IEnumerable<FeriaVirtualWeb.Models.DataContext.PROCESOVENTA>

<div class="breadcomb-area">
    <div class="row">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <div class="breadcomb-list">
                <div class="row">
                    <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                        <div class="breadcomb-wp">
                            <div class="breadcomb-icon">
                                <i class="notika-icon notika-form"></i>
                            </div>
                            <div class="breadcomb-ctn">
                                <h2>Mis Procesos Locales</h2>
                                <p>Revise sus productos locales vendidos</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- Modal -->
<div class="modal fade modal fade bd-example-modal-lg" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-lg modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header" style="background-color: #00c292">
                <h5 class="modal-title" id="exampleModalCenterTitle"></h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <br />
            <div class="modal-body">
            </div>
        </div>
    </div>
</div>

<div class="card col-6 pr-0 pl-0 ml-2">
    <div class="card-header text-center pr-0 pl-0">
        Procesos Venta Locales
    </div>
    <div class="card-body" id="card-subasta">
        <table class="table">
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.IDPROCESOVENTA)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.FECHA)
                </th>
                <th>
                    @Html.DisplayName("ACCIONES")
                </th>
            </tr>

            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.IDPROCESOVENTA)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.FECHA)
                    </td>
                    <td>
                        <a href="#exampleModalCenter" class="btnVerP btn btn-success notika-btn-success" data-toggle="modal" data-id="@item.IDPROCESOVENTA">Productos Comprados</a>
                        <a href="#exampleModalCenter" class="btnGanancia btn btn-success notika-btn-success" data-toggle="modal" data-id="@item.IDPROCESOVENTA">Ganancias</a>
                    </td>
                </tr>
            }

        </table>
    </div>
</div>

<script>
    $(".btnVerP").click(function () {
        $(".modal-body").load("/Productor/GetProductComprados/" + $(this).data("id"));
    });

    $(".btnGanancia").click(function () {
        $(".modal-body").load("/Productor/GetGananciaLocales/" + $(this).data("id"));
    });
</script>

FeriaVirtual-Web/FeriaVirtualWeb/Views/Productor/GetProductComprados.cshtml
@model IEnumerable<FeriaVirtualWeb.Models.DataContext.PRODUCTO>

@{ 
    Layout = null;
}

<table class="table table-condensed">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.DESCRIPCION)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PRECIO)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CANTIDAD)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CLIENTEINTERNO)
        </th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.DESCRIPCION)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.PRECIO)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CANTIDAD)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CLIENTEINTERNO)
        </td>
    </tr>
}

</table>