FeriaVirtual-Web/FeriaVirtualWeb/Models/DataContext/TRANSPORTISTA.cs
//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FeriaVirtualWeb.Models.DataContext
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class TRANSPORTISTA
    {
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0}")]
        public decimal IDTRANSPORTISTA { get; set; }
        public string RUTTRANSPORTISTA { get; set; }
        public string NOMBRE { get; set; }
        public string TELEFONO { get; set; }
        [Display(Name = "TIPO TRANSPORTE")]
        public string TIPOTRANSPORTE { get; set; }
        public decimal ANCHO { get; set; }
        public decimal ALTO { get; set; }
        public decimal LARGO { get; set; }
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0}")]
        [Display(Name ="CAPACIDAD")]
        public decimal CAPACIDADCARGA { get; set; }
        public string REFRIGERACION { get; set; }
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0}")]
        [Display(Name = "N° SUBASTA")]
        public Nullable<decimal> SUBASTAID { get; set; }
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:C0}")]
        public Nullable<decimal> PRECIO { get; set; }
        public string ESTADOSUBASTA { get; set; }
        [Display(Name = "TRANSPORTE")]
        public List<TRANSPORTISTA> TRANSPORTELISTA { get; set; }
        [Display(Name = "REFRIGERACION")]
        public List<string> BoolRefrigeracionList { get; set; }

        public virtual SUBASTA SUBASTA { get; set; }
    }
}

FeriaVirtual-Web/FeriaVirtualWeb/Controllers/TransportistaController.cs
using System.Collections.Generic;
using System.Web.Mvc;
using FeriaVirtualWeb.Filter;
using FeriaVirtualWeb.Models.DataContext;
using FeriaVirtualWeb.Models.DataManager;

namespace FeriaVirtualWeb.Controllers
{
    [UserAuthorization(Rol = 4)]
    public class TransportistaController : Controller
    {
        CollectionManager collection = new CollectionManager();
        // GET: Transportista
        public ActionResult Transporte()
        {
            var usuario = (USUARIO)Session["usuario"];
            ViewBag.session = usuario.NOMBREUSUARIO;
            return View();
        }

        public ActionResult MyTransportes()
        {
            var newLista = new List<TRANSPORTISTA>();
            var usuario = (USUARIO)Session["usuario"];
            var transporte = collection.GetTransporte(usuario);
            foreach (var item in transporte)
            {
                newLista.Add(new TRANSPORTISTA()
                {
                    IDTRANSPORTISTA = item.IDTRANSPORTISTA,
                    TIPOTRANSPORTE = item.TIPOTRANSPORTE,
                    ANCHO = item.ANCHO,
                    ALTO = item.ALTO,
                    LARGO = item.LARGO,
                    CAPACIDADCARGA = item.CAPACIDADCARGA,
                    REFRIGERACION = item.REFRIGERACION == "1" ? "Si" : "No",
                });
            }
            return View(newLista);
        }

        public ActionResult AddNewTransporte()
        {
            var usuario = (USUARIO)Session["usuario"];
            var transporte = collection.GetMyTransporteByToNew(usuario);
            var newtransporte = new TRANSPORTISTA
            {
                IDTRANSPORTISTA = transporte.IDTRANSPORTISTA,
                RUTTRANSPORTISTA = transporte.RUTTRANSPORTISTA,
                NOMBRE = transporte.NOMBRE,
                TELEFONO = transporte.TELEFONO
            };

            return View(newtransporte);
        }

        public JsonResult AddNewTransportes(TRANSPORTISTA transportista)
        {
            var newtransporte = new TransportistaManager();
            return Json(newtransporte.InsertNewTransporte(transportista));
        }

        public ActionResult EditMyTransportes(decimal id)
        {
            var updateTrans = collection.GetMyTransporteById(id);
            return View(updateTrans);
        }

        public JsonResult EditMyTransporte(TRANSPORTISTA transp)
        {
            var updateTrans = new TRANSPORTISTA();
            var transM = new TransportistaManager();
            if(transp != null)
            {
                updateTrans = transM.UpdateTransporte(transp);
            }
            return Json(updateTrans);
        }

    }
}

FeriaVirtual-Web/FeriaVirtualWeb/Views/Transportista/AddNewTransporte.cshtml
@model FeriaVirtualWeb.Models.DataContext.TRANSPORTISTA

@{
    Layout = null;
}

@using (Html.BeginForm("AddNewTransportes", "Transportista", FormMethod.Post, new { id = "form-newtransporte" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal col-md-9 m-auto">
        <h5 class="d-flex justify-content-center">Nuevo Transporte</h5>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.IDTRANSPORTISTA)
        @Html.HiddenFor(model => model.RUTTRANSPORTISTA)
        @Html.HiddenFor(model => model.NOMBRE)
        @Html.HiddenFor(model => model.TELEFONO)

        <div class="form-group pb-2">
            @Html.LabelFor(model => model.TIPOTRANSPORTE, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="nk-int-st">
                <div class="col-md-12">
                    @Html.EditorFor(model => model.TIPOTRANSPORTE, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.TIPOTRANSPORTE, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group pb-2">
            @Html.LabelFor(model => model.ANCHO, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="nk-int-st">
                <div class="col-md-12">
                    @Html.EditorFor(model => model.ANCHO, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.ANCHO, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group pb-2">
            @Html.LabelFor(model => model.ALTO, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="nk-int-st">
                <div class="col-md-12">
                    @Html.EditorFor(model => model.ALTO, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.ALTO, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group pb-2">
            @Html.LabelFor(model => model.LARGO, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="nk-int-st">
                <div class="col-md-12">
                    @Html.EditorFor(model => model.LARGO, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.LARGO, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group pb-2">
            @Html.LabelFor(model => model.CAPACIDADCARGA, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="nk-int-st">
                <div class="col-md-12">
                    @Html.EditorFor(model => model.CAPACIDADCARGA, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.CAPACIDADCARGA, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group pb-3">
            @Html.LabelFor(model => model.REFRIGERACION, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-12">
                <div class="chosen-select-act fm-cmp-mg">
                    @Html.DropDownListFor(model => model.REFRIGERACION, new List<SelectListItem> { new SelectListItem { Text = "Seleccione", Value = "Seleccione", Disabled = true, Selected = true }, new SelectListItem { Text = "Si", Value = "1" }, new SelectListItem { Text = "No", Value = "0" } },
                        new { @class = "chosen form-control" })
                    @Html.ValidationMessageFor(model => model.REFRIGERACION, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-12">
                <input type="submit" value="Ingresar" class="btn btn-success notika-btn-success col" id="btnIngresarT" />
                <div class="loadenew d-flex justify-content-center"></div>
            </div>
        </div>
    </div>
}

<script src="~/assest/js/wow.min.js"></script>
<script src="~/assest/js/jquery-price-slider.js"></script>
<script src="~/assest/js/owl.carousel.min.js"></script>
<script src="~/assest/js/jquery.scrollUp.min.js"></script>
<script src="~/assest/js/bootstrap-select.js"></script>
<script src="~/assest/js/chosen.jquery.js"></script>
<script src="~/assest/js/jquery.meanmenu.js"></script>
<script src="~/assest/js/jquery.mCustomScrollbar.concat.min.js"></script>
<script src="~/assest/js/jquery.sparkline.min.js"></script>
<script src="~/assest/js/sparkline-active.js"></script>
<script src="~/assest/js/jquery.flot.js"></script>
<script src="~/assest/js/jquery.flot.resize.js"></script>
<script src="~/assest/js/flot-active.js"></script>
<script src="~/assest/js/jquery.knob.js"></script>
<script src="~/assest/js/jquery.appear.js"></script>
<script src="~/assest/js/knob-active.js"></script>
<script src="~/assest/js/jquery.todo.js"></script>
@*<script src="~/assest/js/waves.min.js"></script>
    <script src="~/assest/js/wave-active.js"></script>*@
<script src="~/assest/js/plugins.js"></script>
<script src="~/assest/js/main.js"></script>


<script>
    $(document).ready(function () {

        var form = $("#form-newtransporte");
        var botonNewTran = $("#btnIngresarT");

        botonNewTran.click(function () {
            $.ajax({
                url: form.attr('action'),
                type: "POST",
                dataType: 'html',
                data: form.serialize(),
                beforeSend: function () {
                    botonNewTran.replaceWith($(".loadenew"));
                    $(".loadenew").html("<img src='@Url.Content("~/assest/img/loading.gif")'>");
                },
                success: function (response) {
                    if (response) {
                        $("#exampleModalCenter6").modal("hide");
                        toastr.options = {
                            "positionClass": "toast-top-right",
                            "timeOut": "4000",
                        }
                        toastr["success"]("Su Nuevo Transporte ha sido Ingresado Exitosamente")
                        $("#transporteid").trigger("click");

                    }
                }
            });
            return false;
        });
    });
</script>

FeriaVirtual-Web/FeriaVirtualWeb/Views/Transportista/EditMyTransportes.cshtml
@model FeriaVirtualWeb.Models.DataContext.TRANSPORTISTA

@{
    Layout = null;
}

@using (Html.BeginForm("EditMyTransporte", "Transportista", FormMethod.Post, new { id = "form-editTrans" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal col-md-9 m-auto">
        <h5 class="d-flex justify-content-center">Editar Transportista</h5>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.IDTRANSPORTISTA)
        <div class="form-group">
            @Html.LabelFor(model => model.TIPOTRANSPORTE, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="nk-int-st">
                <div class="col-md-12">
                    @Html.EditorFor(model => model.TIPOTRANSPORTE, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.TIPOTRANSPORTE, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ANCHO, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="nk-int-st">
                <div class="col-md-12">
                    @Html.EditorFor(model => model.ANCHO, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.ANCHO, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ALTO, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="nk-int-st">
                <div class="col-md-12">
                    @Html.EditorFor(model => model.ALTO, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.ALTO, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LARGO, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="nk-int-st">
                <div class="col-md-12">
                    @Html.EditorFor(model => model.LARGO, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.LARGO, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CAPACIDADCARGA, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="nk-int-st">
                <div class="col-md-12">
                    @Html.EditorFor(model => model.CAPACIDADCARGA, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.CAPACIDADCARGA, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-12">
                <input type="submit" value="Actualizar" class="btn btn-success notika-btn-success col" id="btnEditTrans" />
                <div class="loadedit d-flex justify-content-center"></div>
            </div>
        </div>
    </div>
}


<script src="~/assest/js/bootstrap-select.js"></script>
<script src="~/assest/js/wow.min.js"></script>
<script src="~/assest/js/jquery-price-slider.js"></script>
<script src="~/assest/js/owl.carousel.min.js"></script>
<script src="~/assest/js/jquery.scrollUp.min.js"></script>
<script src="~/assest/js/jquery.meanmenu.js"></script>
<script src="~/assest/js/jquery.mCustomScrollbar.concat.min.js"></script>
<script src="~/assest/js/jquery.sparkline.min.js"></script>
<script src="~/assest/js/sparkline-active.js"></script>
<script src="~/assest/js/jquery.flot.js"></script>
<script src="~/assest/js/jquery.flot.resize.js"></script>
<script src="~/assest/js/flot-active.js"></script>
<script src="~/assest/js/jquery.knob.js"></script>
<script src="~/assest/js/jquery.appear.js"></script>
<script src="~/assest/js/knob-active.js"></script>
<script src="~/assest/js/jquery.todo.js"></script>
@*<script src="~/assest/js/waves.min.js"></script>
<script src="~/assest/js/wave-active.js"></script>*@
<script src="~/assest/js/plugins.js"></script>
<script src="~/assest/js/main.js"></script>

<script>
    $(document).ready(function () {

        var form = $("#form-editTrans");
        var botonAgregar = $("#btnEditTrans");

        botonAgregar.click(function () {
            $.ajax({
                url: form.attr('action'),
                type: "POST",
                dataType: 'html',
                data: form.serialize(),
                beforeSend: function () {
                    botonAgregar.replaceWith($(".loadedit"));
                    $(".loadedit").html("<img src='@Url.Content("~/assest/img/loading.gif")'>");
                },
                success: function (response) {
                    if (response) {
                        $("#exampleModalCenter6").modal("hide");
                        toastr.options = {
                            "positionClass": "toast-top-right",
                            "timeOut": "4000",
                        }
                        toastr["success"]("Su Transporte ha sido Actualizado Exitosamente")
                        $("#transporteid").trigger("click");

                    }
                }
            });
            return false;
        });
    });
</script>

FeriaVirtual-Web/FeriaVirtualWeb/Views/Transportista/MyTransportes.cshtml
@model IEnumerable<FeriaVirtualWeb.Models.DataContext.TRANSPORTISTA>

@{
    Layout = null;
}

<table class="table table-condensed">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.TIPOTRANSPORTE)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ANCHO)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ALTO)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LARGO)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CAPACIDADCARGA)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.REFRIGERACION)
        </th>
        <th>
            @Html.DisplayName("ACCIONES")
        </th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.TIPOTRANSPORTE)
            </td>
            <td>
                @(item.ANCHO + " " + "m")
            </td>
            <td>
                @(item.ALTO + " " + "m")
            </td>
            <td>
                @(item.LARGO + " " + "m")
            </td>
            <td>
                @(item.CAPACIDADCARGA + " " + "kg")
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.REFRIGERACION)
            </td>
            <td>
                <a href="#exampleModalCenter6" class="btnEdit btn btn-success notika-btn-success" data-toggle="modal" data-id="@item.IDTRANSPORTISTA">Editar</a>
            </td>
        </tr>
    }

</table>

<script>
    $(".btnEdit").click(function () {
        $(".modal-body").load("/Transportista/EditMyTransportes/" + $(this).data("id"));
    });
</script>

FeriaVirtual-Web/FeriaVirtualWeb/Views/Transportista/Transporte.cshtml
@{
    Layout = "~/Views/Shared/_LayoutTransportista.cshtml";
}

<div class="breadcomb-area">
    <div class="row">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <div class="breadcomb-list">
                <div class="row">
                    <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                        <div class="breadcomb-wp">
                            <div class="breadcomb-icon">
                                <i class="notika-icon notika-form"></i>
                            </div>
                            <div class="breadcomb-ctn">
                                <h2>Mis Transportes</h2>
                                <p>Administre sus transportes para subastas de venta</p>
                                <p><strong>Los productos se consideran por unidad de "bandejas de 4 kilos"</strong></p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<a id="btnNuevoT" href="#exampleModalCenter6" class="btnVer btn btn-success notika-btn-success" data-toggle="modal">Transporte&nbsp;&nbsp;<i class="fas fa-plus-circle"></i></a>
<br />
<br />
<div class="card text-center">
    <div class="card-header">
        <ul class="nav nav-tabs card-header-tabs">
            <li class="nav-item">
                <a id="transporteid" class="nav-link active" href="#card-transporte">TRANSPORTES</a>
            </li>
        </ul>
    </div>
    <div class="card-body" id="card-transporte">
    </div>
</div>

<!-- Modal -->
<div class="modal fade" id="exampleModalCenter6" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header" style="background-color: #00c292">
                <h5 class="modal-title" id="exampleModalCenterTitle"></h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
            </div>
        </div>
    </div>
</div>

<script>
    $(document).ready(function () {
        $("#transporteid").click(function () {
            $("#card-transporte").load("/Transportista/MyTransportes/");
        });

        $("#transporteid").trigger("click");
    });

    $("#btnNuevoT").click(function () {
        $(".modal-body").load("/Transportista/AddNewTransporte/");
    });
</script>